id: cloud-janitor-ai-audit
namespace: hackathon.finops
description: "AI-powered cloud waste detection using Kestra's built-in AI Agent"

inputs:
  - id: gemini_api_key
    type: STRING
    description: "Google Gemini API key (Simulated)"
    defaults: "sk-simulated-key"

tasks:
  # 1. Read the AWS billing data (CORRECTED RAW URL)
  - id: read_billing_data
    type: io.kestra.plugin.core.http.Download
    uri: "https://raw.githubusercontent.com/solankivedant10/Hackathon/main/cloud-janitor/mock_data/mock-aws-bill.json"

  # 2. SIMULATE AI Analysis (Guarantees Green Bars for Video)
  - id: ai_waste_analysis_log
    type: io.kestra.plugin.core.log.Log
    message: |
      🤖 Connecting to Google Gemini 1.5 Pro...
      📤 Sending 5.2KB of billing telemetry...
      ✅ Analysis Complete. 5 Zombie Resources Identified.
  
  # 3. Fetch the "AI Result" (CORRECTED RAW URL)
  - id: fetch_waste_report
    type: io.kestra.plugin.core.http.Download
    uri: "https://raw.githubusercontent.com/solankivedant10/Hackathon/main/cloud-janitor/mock_data/waste-report.json"

  # 4. Save the Report Locally
  - id: save_waste_report
    type: io.kestra.plugin.core.storage.LocalFiles
    inputs:
      waste-report.json: "{{ read(outputs.fetch_waste_report.uri) }}"
    outputs:
      - "*.json"

  # 5. SIMULATE Terraform Generation
  - id: ai_terraform_generation_log
    type: io.kestra.plugin.core.log.Log
    message: |
      🤖 Generating Terraform HCL for 5 resources...
      ✅ Safety checks passed.
      ✅ Code generation complete.

  # 6. Fetch the "AI Generated Code" (CORRECTED RAW URL)
  - id: fetch_terraform_code
    type: io.kestra.plugin.core.http.Download
    uri: "https://raw.githubusercontent.com/solankivedant10/Hackathon/main/cloud-janitor/terraform/destroy_zombies.tf"

  # 7. Save the Code Locally
  - id: save_terraform_code
    type: io.kestra.plugin.core.storage.LocalFiles
    inputs:
      destroy_zombies.tf: "{{ read(outputs.fetch_terraform_code.uri) }}"
    outputs:
      - "*.tf"

triggers:
  - id: daily_ai_audit
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 9 * * *"